### ISSUE TITLE
Improved IPS error handling

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#11]
Here are some use cases where it'd be great to see some more robust error handling within the IPS (mostly to handle poorly configured config files or badly written wrappers) ...

* Fatal errors posted to the top level log file specified in --log=this.log at the IPS call.
* Full paths to missing files.
* Full path to log file containing the most recent error.
* Add line breaks after FRAMEWORK errors so they don't mix with the Python stack trace.
* IPS pre-processor to find missing files and check configuration sanity.
* Check to see if the PYTHONPATH is set correctly to include the required wrapper classes.
* Check to see if file specified by "SCRIPT" exists, rather than just telling me that the python module cannot be found (which could be related to something else, i.e., the "NAME" variable).
* Exit on wrapper error, rather than continuing the IPS simulation (yeah, hard to do if the wrappers are poorly written)

I realize some of these may be difficult to implement, but anything we can do that aids in tracking errors will save us a lot of time in the long run.

**Comment by bernhold** [comment]
In terms of how to use the ticket tracker, I wonder if these should be 
broken down into individual tickets?  It seems like it would be easier 
to discuss and track the feasibility and implementation of each idea 
separately.

On 5/11/2015 10:14 AM, David L Green wrote:
> Here are some use cases where it'd be great to see some more robust
> error handling within the IPS (mostly to handle poorly configured config
> files or badly written wrappers) ...
>
>   * Fatal errors posted to the top level log file specified in
>     --log=this.log at the IPS call.
>   * Full paths to missing files.
>   * Full path to log file containing the most recent error.
>   * Add line breaks after FRAMEWORK errors so they don't mix with the
>     Python stack trace.
>   * IPS pre-processor to find missing files and check configuration sanity.
>   * Check to see if the PYTHONPATH is set correctly to include the
>     required wrapper classes.
>   * Check to see if file specified by "SCRIPT" exists, rather than just
>     telling me that the python module cannot be found (which could be
>     related to something else, i.e., the "NAME" variable).
>   * Exit on wrapper error, rather than continuing the IPS simulation
>     (yeah, hard to do if the wrappers are poorly written)
>
> I realize some of these may be difficult to implement, but anything we
> can do that aids in tracking errors will save us a lot of time in the
> long run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ORNL-Fusion/ips-atom/issues/11>.
>


-- 
David E. Bernholdt                | Email: bernholdtde@ornl.gov
Oak Ridge National Laboratory     | Phone: +1 865-574-3147
http://www.csm.ornl.gov/~bernhold | Fax:   +1 865-576-5491

**Comment by dlg0** [comment]
Sure. I'll start with just one.
