### ISSUE TITLE
Find run directory from SWIM portal?

### ISSUE THREAD

**Issue by murakamim** [ORNL-Fusion/ips-atom#13]
How do I determine the run directory at NERSC from the SWIM portal?

**Comment by elwasif** [comment]
@dlg0 Right now there's no way to get that information from the portal. We can think about adding that information to the Host field, but we'll have to consider if this is an acceptable security and privacy practice (the portal is open to everybody and maybe some will not want this information out there).

**Comment by murakamim** [comment]
Thank you, Wael.  I normally keeping this info in my own readfme file in my run area when the PORTAL_ID is known.  As you said, there may be security and privacy practice, although I myself does not mind.  Thanks again,
Masanori
