### ISSUE TITLE
run11 failed immediately

### ISSUE THREAD

**Issue by murakamim** [ORNL-Fusion/ips-atom#14]
I ran /run11/ second time  by changing innubeam, but failed immediately, while the first attempt was successful with a wrong innubeam a week ago.  The pathe is:
/scratch1/scratchdirs/murakami/d3d02/111203.02505/tglf/run11_error

**Comment by parkjm** [comment]
@murakamim  There was accident that deleted all binaries related to fastran. It seems not fully recovered last Friday. Please try it again.

**Comment by dlg0** [comment]
That accident was my fault :) Apologies.

**Comment by murakamim** [comment]
Thank you, JM.  That is clear.  I will try again.  Similarly I had the same experience in the next run /run12/ which went a little further but failed at 137s.  Then the third one, run15/ (submitted onetime later).went through OK with successful completion These sequential events would be explained by your reasoning.  Thanks again,
Masanori
