### ISSUE TITLE
/run11/ failure after resubmission

### ISSUE THREAD

**Issue by murakamim** [ORNL-Fusion/ips-atom#18]
Upon suggestion by JM for resubmitting previous jobs (accidental absence of the binaries) , I could complete two job outs of the three previously-failed jobs, but only one remaiining job /run11/ (or equivalent run11_error/):
/scra/scratch1/scratchdirs/murakami/d3d02/111203.02505/tglf/run11_error 
still keeps  failing (with e.g., SWIM IDs: 34655). About two weeks ago the same case (except a wrong setting in innubeam) ran successfully.  Thank you,

**Comment by parkjm** [comment]
Again, it seems that the Friday accident had not been recovered fully. Hopefully recovered this time. Please try it again.
