### ISSUE TITLE
Portal - Data not available: Cannot download monitor NetCDF file

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#20]
@ORNL-Fusion/ips-support-team 

My runs have been putting data in 

`/project/projectdirs/atom/www/greendl1`

and I'd noticed on the portal a message 

`Data not available: Cannot download monitor NetCDF file`

So I added `a+w` permissions to that directory and its contents but I still get the same error.

How do I fix my www directory such that the portal can display my run data?

Thanks.

**Comment by elwasif** [comment]
You don't have o+rx

drwxr-sr-x  2 elwasif  atom    512 Feb 24 08:34 elwasif
drwxrws---+ 2 greendl1 atom 131072 May 13 09:53 greendl1

**Comment by dlg0** [comment]
Hmmm ... still seems to not be working ...

```
greendl1@edison01:/project/projectdirs/atom/www> ls -alh
total 512K
drwxrwsr-x  6 greendl1 atom  512 Apr 13 14:07 .
drwxrwsr-x  9 greendl1 atom 128K May  7 07:40 ..
drwxr-sr-x  2 u2115    atom  512 Feb 25 11:40 dbb
drwxr-sr-x  2 elwasif  atom  512 Feb 24 08:34 elwasif
drwxrwsr-x+ 2 greendl1 atom 128K May 13 11:57 greendl1
drwxr-sr-x  2 diemsj   atom  512 Mar 24 08:45 sjd
```

**Comment by elwasif** [comment]
On 05/13/2015 03:12 PM, David L Green wrote:
> Hmmm ... still seems to not be working ...
>
> |greendl1@edison01:/project/projectdirs/atom/www> ls -alh
> total 512K
> drwxrwsr-x  6 greendl1 atom  512 Apr 13 14:07 .
> drwxrwsr-x  9 greendl1 atom 128K May  7 07:40 ..
> drwxr-sr-x  2 u2115    atom  512 Feb 25 11:40 dbb
> drwxr-sr-x  2 elwasif  atom  512 Feb 24 08:34 elwasif
> drwxrwsr-x+ 2 greendl1 atom 128K May 13 11:57 greendl1
> drwxr-sr-x  2 diemsj   atom  512 Mar 24 08:45 sjd
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ORNL-Fusion/ips-atom/issues/20#issuecomment-101780531>.
>
It won't help with old runs, the portal retrieves files as the job is 
running, it won't go back and try to retreive files for jobs that had 
terminated.

http://portal.nersc.gov/project/atom/greendl1/

is visible to the outside world now, so it should work if your 
configuration file has paths set correctly

-- 
Wael R. Elwasif, PhD.
Research Staff Member
Computer Science Research Group
Oak Ridge National Laboratory
P.O. Box 2008, Bldg. 5600, MS 6016
Oak Ridge, TN 37831-6016

Office : (865)241-0002
Fax:     (865)576-5491

**Comment by dlg0** [comment]
Thanks.
