### ISSUE TITLE
services.info 

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#27]
@elwasif 

I've implemented services.info('msg text') in a few places, but have noticed that the output does not appear in the logs. I have the debug level set to WARNING, and had figured that DEBUG encompassed all other levels, and WARNING all levels above that, but perhaps not? Do I also have to specify the INFO debug level in addition?

**Comment by elwasif** [comment]
Actually info is at a level higher than debug, but lower than warning, so it won't appear if you set the LOG_LEVEL to WARNING. I usually use services.warning() when I want something to appear. You can set LOG_LEVEL to INFO to show anything higher than or equal to info

**Comment by dlg0** [comment]
OK. I'll just use services.warning() also. Thanks.
