### ISSUE TITLE
Run doesn't get started.

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#28]
@elwasif @batchelordb 

The IPS run skeleton in the following directory seems to get stuck in the initialization phase and I've thus far been unable to figure out what I've done to cause such a thing.

```
/project/projectdirs/atom/users/greendl1/diem_fastran_does_nothing
```

The directory is a skeleton and needs to be run, so if you're so inclined, please copy it to your location of choice and just run 

```
qsub batchscript.ips.edison
```

You'll see in `log.stdOut` that is doesn't log anything past the `__init__` call to the fastran_init component.

Thanks.

**Comment by elwasif** [comment]
Here's what I get

$> $cp -rf /project/projectdirs/atom/users/greendl1/diem_fastran_does_nothing .
$> cd  /project/projectdirs/atom/users/greendl1/diem_fastran_does_nothing
$> qsub batchscript.ips.edison
$>  more log.framework
2015-07-24 03:52:29,459 FRAMEWORK       ERROR    Error accessing configuration section for
 component fastran_driver in simulation thisSim
Traceback (most recent call last):
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 584, in _initialize_sim
    comp_conf = sim_conf[comp_ref]
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py",
 line 567, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'fastran_driver'

**Comment by dlg0** [comment]
So it turns out I'm just an idiot. I must have looked in all the log files except that one for some reason. Thanks for pointing out my mistake :)
