### ISSUE TITLE
CLASS and SUB_CLASS config file uses?

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#4]
@ORNL-Fusion/ips-support-team What are the CLASS and SUB_CLASS variables within the config file for each component used for?

**Comment by elwasif** [comment]
@dlg0 Categorization for the kind of physics that the component does, and used to disambiguate the working directory in work/ - comes in handy when the same code  is used to do different things in the same simulation.

**Comment by dlg0** [comment]
Thanks.
